services:
  api: # nombres que le asignamos a los contenedores
    build: # con esto se le dice construi la imagen de esta misma ruta
      context: . # para dev, indicarle al dev donde se encuentra la app donde va a trabajar
      dockerfile: Dockerfile  # Le indica que cree la api pero desde dockerfile dev
    container_name: plataforma_api_dev
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - .:/app #red interna
    ports:
      - "3000:3000" # primer puerto del anfitrion, segundo puerto del contendor
    environment:
      - ENVIRONMENT=dev
    depends_on:
      - db
      - jaeger

  db:
    image: postgres:15-alpine
    container_name: plataforma_db_dev
    restart: always
    environment:
      - POSTGRES_USER=postgres #asi hardcodeado no va, se tiene que subir desde un archivo .env
      - POSTGRES_PASSWORD=thisisshit
      - POSTGRES_DB=plataforma_dev
    ports:
      - "5433:5432"
    volumes: # indica al contenedor que volumes va a utilizar
      - postgres_data_dev:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: plataforma_jaeger_dev
    ports:
      - "16686:16686" # UI de Jaeger (entr√°s por navegador)
      - "6831:6831/udp" # Puerto para enviar trazas
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes: #se usa para la persistencia de datos, para no perder datos en caso de borrar imagenes
  postgres_data_dev: